# repo wide development config
[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.flake8]
ignore = "E501,E101,W191" # line length
max-line-length = 88
max-complexity = 18

[tool.pycln]
all = true
